/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SectorLog {
    id: string;
    title: string;
    body: string;
    date: string;
    sector: string;
    level: bigint;
    author: string;
}
export interface MenuItem {
    id: string;
    name: string;
    createdBy: string;
    description: string;
    stock: bigint;
    price: number;
    facility: string;
}
export interface AdminPost {
    id: string;
    content: string;
    date: string;
    minLvl: bigint;
    sector: string;
    author: string;
}
export interface ActivityEntry {
    ts: string;
    msg: string;
}
export interface User {
    uid: string;
    question: string;
    name: string;
    answer: string;
    level: bigint;
}
export interface Transaction {
    id: string;
    ts: string;
    member: string;
    changedBy: string;
    description: string;
    newAmount: number;
    prevAmount: number;
}
export interface backendInterface {
    addActivity(msg: string, ts: string): Promise<void>;
    addAdminPost(author: string, content: string, minLvl: bigint, date: string, sector: string): Promise<string>;
    addMenuItem(facility: string, name: string, price: number, description: string, createdBy: string, stock: bigint): Promise<string>;
    addSectorLog(sector: string, title: string, body: string, author: string, level: bigint, date: string): Promise<string>;
    addTransaction(member: string, prevAmount: number, newAmount: number, changedBy: string, ts: string, description: string): Promise<string>;
    clearBroadcast(): Promise<void>;
    clearOldActivities(): Promise<void>;
    deleteAdminPost(id: string): Promise<void>;
    deleteMenuItem(id: string): Promise<void>;
    deleteSectorLog(id: string): Promise<void>;
    deleteUser(name: string): Promise<void>;
    getActivities(): Promise<Array<ActivityEntry>>;
    getAdminPosts(sector: string): Promise<Array<AdminPost>>;
    getAllAdminPosts(): Promise<Array<AdminPost>>;
    getAllMemberExtras(): Promise<Array<[string, string]>>;
    getAllMemberFunds(): Promise<Array<[string, number]>>;
    getAllMenuItemExtras(): Promise<Array<[string, string]>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllSectorLogs(): Promise<Array<SectorLog>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUsers(): Promise<Array<[string, bigint]>>;
    getAllXutNumbers(): Promise<Array<[string, string]>>;
    getBroadcast(): Promise<string>;
    getCardNumber(name: string): Promise<string>;
    getContent(key: string): Promise<string>;
    getLockdown(): Promise<boolean>;
    getMemberExtras(name: string): Promise<string>;
    getMemberFunds(name: string): Promise<number>;
    getMemberTransactions(member: string): Promise<Array<Transaction>>;
    getMenuItemExtras(id: string): Promise<string>;
    getMenuItems(facility: string): Promise<Array<MenuItem>>;
    getOfficeLocations(): Promise<string>;
    getSectorLogs(sector: string): Promise<Array<SectorLog>>;
    getSecurityQuestion(name: string): Promise<string>;
    getUserCount(): Promise<bigint>;
    getXutNumber(name: string): Promise<string>;
    loginUser(name: string, answer: string): Promise<User>;
    registerUser(name: string, question: string, answer: string): Promise<void>;
    renameUser(oldName: string, newName: string, question: string, answer: string, level: bigint, uid: bigint): Promise<void>;
    setBroadcast(msg: string): Promise<void>;
    setCardNumber(name: string, cardNum: string): Promise<void>;
    setContent(key: string, value: string): Promise<void>;
    setLockdown(active: boolean): Promise<void>;
    setMemberExtras(name: string, json: string): Promise<void>;
    setMemberFunds(name: string, amount: number): Promise<void>;
    setMenuItemExtras(id: string, json: string): Promise<void>;
    setOfficeLocations(json: string): Promise<void>;
    setUserLevel(name: string, level: bigint): Promise<void>;
    setXutNumber(name: string, xutNum: string): Promise<void>;
    updateAdminPost(id: string, newContent: string): Promise<void>;
    updateMenuItemStock(id: string, newStock: bigint): Promise<void>;
    updateSectorLog(id: string, newBody: string): Promise<void>;
    updateUserLevel(name: string, newLevel: bigint): Promise<void>;
    updateUserPassword(name: string, newAnswer: string): Promise<void>;
    updateUserQuestion(name: string, newQuestion: string): Promise<void>;
    userExists(name: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, arg1);
            return result;
        }
    }
    async addAdminPost(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPost(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPost(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: string, arg2: number, arg3: string, arg4: string, arg5: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addSectorLog(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSectorLog(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSectorLog(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: number, arg2: number, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async clearBroadcast(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearBroadcast();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearBroadcast();
            return result;
        }
    }
    async clearOldActivities(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOldActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOldActivities();
            return result;
        }
    }
    async deleteAdminPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdminPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdminPost(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteSectorLog(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSectorLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSectorLog(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getActivities(): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities();
            return result;
        }
    }
    async getAdminPosts(arg0: string): Promise<Array<AdminPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPosts(arg0);
            return result;
        }
    }
    async getAllAdminPosts(): Promise<Array<AdminPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminPosts();
            return result;
        }
    }
    async getAllMemberExtras(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemberExtras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemberExtras();
            return result;
        }
    }
    async getAllMemberFunds(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemberFunds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemberFunds();
            return result;
        }
    }
    async getAllMenuItemExtras(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItemExtras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItemExtras();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAllSectorLogs(): Promise<Array<SectorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSectorLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSectorLogs();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllXutNumbers(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllXutNumbers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllXutNumbers();
            return result;
        }
    }
    async getBroadcast(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBroadcast();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBroadcast();
            return result;
        }
    }
    async getCardNumber(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardNumber(arg0);
            return result;
        }
    }
    async getContent(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent(arg0);
            return result;
        }
    }
    async getLockdown(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getLockdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLockdown();
            return result;
        }
    }
    async getMemberExtras(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberExtras(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberExtras(arg0);
            return result;
        }
    }
    async getMemberFunds(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberFunds(arg0);
            return result;
        }
    }
    async getMemberTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberTransactions(arg0);
            return result;
        }
    }
    async getMenuItemExtras(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemExtras(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemExtras(arg0);
            return result;
        }
    }
    async getMenuItems(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return result;
        }
    }
    async getOfficeLocations(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficeLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficeLocations();
            return result;
        }
    }
    async getSectorLogs(arg0: string): Promise<Array<SectorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectorLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectorLogs(arg0);
            return result;
        }
    }
    async getSecurityQuestion(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityQuestion(arg0);
            return result;
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async getXutNumber(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getXutNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getXutNumber(arg0);
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async renameUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameUser(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameUser(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async setBroadcast(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBroadcast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBroadcast(arg0);
            return result;
        }
    }
    async setCardNumber(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCardNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCardNumber(arg0, arg1);
            return result;
        }
    }
    async setContent(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContent(arg0, arg1);
            return result;
        }
    }
    async setLockdown(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLockdown(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLockdown(arg0);
            return result;
        }
    }
    async setMemberExtras(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMemberExtras(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMemberExtras(arg0, arg1);
            return result;
        }
    }
    async setMemberFunds(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMemberFunds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMemberFunds(arg0, arg1);
            return result;
        }
    }
    async setMenuItemExtras(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMenuItemExtras(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMenuItemExtras(arg0, arg1);
            return result;
        }
    }
    async setOfficeLocations(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOfficeLocations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOfficeLocations(arg0);
            return result;
        }
    }
    async setUserLevel(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserLevel(arg0, arg1);
            return result;
        }
    }
    async setXutNumber(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setXutNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setXutNumber(arg0, arg1);
            return result;
        }
    }
    async updateAdminPost(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPost(arg0, arg1);
            return result;
        }
    }
    async updateMenuItemStock(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItemStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItemStock(arg0, arg1);
            return result;
        }
    }
    async updateSectorLog(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSectorLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSectorLog(arg0, arg1);
            return result;
        }
    }
    async updateUserLevel(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserLevel(arg0, arg1);
            return result;
        }
    }
    async updateUserPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserPassword(arg0, arg1);
            return result;
        }
    }
    async updateUserQuestion(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserQuestion(arg0, arg1);
            return result;
        }
    }
    async userExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.userExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.userExists(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
